version: "3.7"

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.local
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend
